### ISSUE TITLE
make bench doesn't work

### ISSUE THREAD

**Issue by vmrm** [pashcovich/http2_go_bench_test#1]
Status: Downloaded newer image for nginx:1.16
 ---> 0dac5b41d811
Step 7/12 : WORKDIR /root
 ---> Running in 7272c3a48dfc
Removing intermediate container 7272c3a48dfc
 ---> 398a6682b1a9
Step 8/12 : COPY cert.conf ./
COPY failed: stat /var/lib/docker/tmp/docker-builder253008698/cert.conf: no such file or directory
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by pashcovich** [comment]
fixed in https://github.com/pashcovich/http2_go_bench_test/commit/d637017f4cabc2893b42b8f286873db1114d2b74
